### PR TITLE
Group 4

### PR DESCRIPTION
**Pull request by rachaelharris**
Collaborating on changes to be made to the participation section of the Code of Conduct for CMPSC203S2021.

### CODE REVIEW

**Comment by corlettim** [comment]
Please make sure you have a description for your PR. Also you need to be asking for all of the TLs reviews.

**Review by jjumadinova — DISMISSED** [review]
Please fix the merge conflicts, it seems you have some linting issues to resolve.

**Review by noorbuchi — CHANGES_REQUESTED** [review]
Please address the requested changes mentioned above

**Comment by corlettim** [comment]
Great job on getting your checks to pass! Before it can be approved, please add a description and fix the merge conflicts.

**Review by enpuyou — DISMISSED** [review]
The change looks good!

**Review by enpuyou — COMMENTED** [review]
@rachaelharris Can you resolve the conflicts again and we should be able to merge this PR right away. Thanks!

**Review by noorbuchi — CHANGES_REQUESTED** [review]
Everything looks good! Please resolve conflicts and we'll merge this soon.

**Review by corlettim — CHANGES_REQUESTED** [review]
Everything looks good! All you need to do is resolve the merge conflicts

**Review by enpuyou — APPROVED** [review]

**Review by noorbuchi — APPROVED** [review]

**Review by corlettim — APPROVED** [review]

**Pull request merged**
